language: cpp
compiler: gcc
sudo: require
dist: bionic
cache:
  ccache: true
  directories:
  - $HOME/.ccache
  - $HOME/.cache/apt

before_install:
  - mkdir -p $HOME/.cache/apt/partial
  - sudo rm -rf /var/cache/apt/archives
  - sudo ln -s $HOME/.cache/apt /var/cache/apt/archives
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.6-bionic -y
  - sudo apt-get update 

install:
  - sudo apt-get -y install build-essential git qt512-meta-minimal qt512quickcontrols qt512quickcontrols2 qt512svg qt512x11extras qt512graphicaleffects qt512svg libgl1-mesa-dev libmpv-dev libgl1-mesa-dev x11proto-xext-dev libx11-dev python3-setuptools 
  - sudo apt-get build-dep mpv
  - source /opt/qt*/bin/qt*-env.sh

script:
  - time bash scripts/makeappimage.sh

after_success:
  - time bash scripts/upload.sh
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/


