language: cpp
compiler: gcc
sudo: require
dist: xenial
cache:
  ccache: true
  directories:
  - $HOME/.ccache
  - $HOME/.cache/apt
  #- $HOME/.cache/mpv-build

before_install:
  - mkdir -p $HOME/.cache/apt/partial
  - sudo rm -rf /var/cache/apt/archives
  - sudo ln -s $HOME/.cache/apt /var/cache/apt/archives
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y
  - sudo apt-get update 

install:
  - sudo apt-get -y install ccache qt511-meta-minimal qt511quickcontrols python3-setuptools qt511quickcontrols2 qt511svg libgl1-mesa-dev
  - sudo apt-get -y install libavutil-dev libbs2b-dev libegl1-mesa-dev libgl1-mesa-dev libguess-dev liblcms2-dev liblua5.2-dev libpulse-dev librubberband-dev libswscale-dev libuchardet-dev libx11-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxv-dev zlib1g-dev libmp3lame-dev libopus-dev libx264-dev libx265-dev libtheora-dev libtwolame-dev libpulse-dev libopenjpeg-dev libass-dev libgme-dev libwavpack-dev libfribidi-dev libvpx-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - wget https://github.com/NamedKitten/mpv-builder/releases/download/continuous/deps.tar.xz
  - sudo tar xvf deps.tar.xz -C /
  - time bash scripts/makeappimage.sh

after_success:
  - time bash scripts/upload.sh
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/


